- .devops/code-review-pipelines.yml
- .devops/deploy-pipelines.yml
- .github/CODEOWNERS
- .github/PULL_REQUEST_TEMPLATE.md
Add code-review and deploy pipelines
> [RTD-80] Add code-review and deploy pipelines

- .devops/deploy-pipelines.yml
This PR fix a refuse in deploy pipeline.
> [RTD-123] fix deploy pipeline

- manifests/deployment.yml
- manifests/service.yml
This PR propose to add deployment and service manifest.
- add the 2 manifests.
> [RTD-125] Add manifests

- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/model/FileMetadataDTO.java
This PR propose a draft DTO for transferring files' metadata.
> [RTD-127] add file metadata DTO

- pom.xml
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/model/FileMetadataEntity.java
This PR propose to add the File Metadata entity.
- add entity class under model.
The use of an entity class decouples the business logic DTO from the data layer.
The DTO will be mapped to the entity and viceversa.
> [RTD-148] Add file metadata entity

- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/repository/FileMetadataRepository.java
- src/main/resources/application.yml
This PR propose an extension of Spring Boot MongoRepository.
This interface will interact with the business logic with a service and the data layer with a MongoDB instance.
- add MongoRepository interface extension.
- add the connection string to the CSTAR CosmosDB instance. This is placed inside the application properties. The connection string can be customized with an environment variable.
This interface represents the needed abstraction in order to access data inside the database.
> [RTD-149] Add Mongo Spring Boot repository

- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/controller/RestControllerImpl.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/model/FileMetadata.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/model/FileMetadataDTO.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/model/FileMetadataEntity.java
This PR propose a validation on File metadata DTO.
- add a common file metadata class.
- add annotation for validation.
The exchanged object must be validated prior to its storage.
> [RTD-156] Add DTO validation

- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/controller/RestController.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/controller/RestControllerImpl.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/service/FileMetadataService.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/service/FileMetadataServiceImpl.java
This PR propose a Spring service implementation to decouple business layer and data layer.
> [RTD-150] Add Spring service

- Dockerfile
This PR proposes the adoption of a OpenJDK image compatible with arm architecture.
- change JDK image from amd-only to a cross-architecture one.
While building the micro-service image on a arm machine, no manifest for arm were found with the old image.
In order to grant cross-compatibility we had to change the adopted JDK layer.
> [RTD-169] Add cross-architecture JDK

- postman/local_file_register_integration_test.postman_collection.json
This PR proposes to add a Postman collection in order to carry out local integration tests.
The support of a MongoDB repository is needed.
- add Postman collection
Having a Postman collection available, combined with a local deployment, allows you to effectively, consistently and efficiently test the changes made to the code.
> [RTD-170] Add Postman collection

- README.md
This PR proposes an update of the README file, according to the latest updates.
- update README.
The README file in the root of the project must provide the useful commands for performing e2e tests locally.
> [RTD-171] update README

- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/service/FileMetadataServiceTest.java
This PR fixes an issue with an erroneous import of junit instead of junit.jupiter .
- refactor service test
This will make parameterized test possible.
The test will be also recognized by SonarCloud.
> [RTD-175] Update Junit version testing service

- lombok.config
This PR propose a way to exclude Lombok-generated code from coverage.
- add Lombok configuration to exclude auto-generated code from coverage.
This change was needed in order to have realistic code coverage results.
> [RTD-175] Exclude Lombok code from code coverage

- pom.xml
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/event/EventHandler.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/event/EventHandlerTest.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/service/FileMetadataServiceTest.java
- src/test/resources/application-test.yml
This PR proposes an event handler base structure.
- an event handler with functional logic.
- event handler test
- test application properties
- maven checkstyle plugin
- service test refactor
An event handler is needed in order to process Event Grid events.
The functional logic is introduced to accomplish an ETL logic.
> [RTD-173] Add event handler

- manifests/deployment.yml
- src/main/resources/application.yml
- src/test/resources/application-test.yml
This PR proposes the addition of the needed bindings in order to connect the micro-service to queues.
- add kafka bindings in application properties
- add secret reference in deployment manifest
With this change the micro-service is capable of receiving events from rtd-platform-events in DEV environment.
> [RTD-172] Connect to Event Grid

- docker-compose.yml
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/adapter/BlobRegisterAdapter.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/event/EventHandler.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/model/FileMetadata.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/event/EventHandlerTest.java
This PR proposes to add a basic implementation of a queue-to-service adapter.
- add adapter
- update event handler
- add event handler and adapter test
- add timestamps to file metadata (not validated yet)
- fix docker compose
This change allow a basic assessment of the capabilities of the micro-service in terms of cross-interface data exchange.
A basic structure of pattern matching on blob container name is done to skim events not of interest.
> [RTD-181] Add adapter from queue to service

- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/adapter/BlobRegisterAdapter.java
This PR proposes to add a status enumeration with get method to retrieve its numeral form.
- add STATUS enumeration in adapter
This change allows us to associate a status in a verbose way.
Further updates and additions will be simplified by the way it is managed (inside only one class).
> [RTD-187] Add file status enumeration

- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/model/FileMetadata.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/controller/RestControllerTest.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/service/FileMetadataServiceTest.java
This PR proposes to update file metadata model to latest design.
- update model
- update tests
The object that represents the data must be adapted to the latest specification produced by the system design.
The subject fields will be common to all files observed by the register file.
> [TAE-90] Update file metadata model

- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/adapter/BlobRegisterAdapter.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/event/EventHandlerTest.java
This PR proposes to update file status enumeration to latest design.
- update status enumeration
- remove flaky tests
The object that represents the status of a file must be adapted to the latest specification produced by the system design.
> [TAE-94] Update status enumeration

- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/adapter/BlobRegisterAdapter.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/event/EventHandler.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/model/FileStatus.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/model/FileType.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/event/EventHandlerTest.java
This PR proposes to add file type enumeration, according to latest design.
- add type enumeration file
- move status to enumeration file
- refactor container evaluation
This change introduce a way to distinguish file types using destination container.
> [TAE-95] Add file type enumeration

- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/adapter/BlobRegisterAdapter.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/model/FileApplication.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/model/FileStatus.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/model/FileType.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/event/EventHandlerTest.java
This PR proposes to add file application enumeration, according to latest design.
- add application enumeration file
- add application evaluation mechanism
- update test
- refactor other enumerations
This change introduce a way to distinguish file application using file type.
> [TAE-96] Add file application enumeration

- .devops/deploy-pipelines.yml
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/adapter/BlobRegisterAdapter.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/event/EventHandlerTest.java
This PR proposes to add a mechanic by which, given a filename and its type, the parent file is inferred.
- add parent extraction logic
- update test
This change allow us to store a reference to the file that originated the event.
> [TAE-119] Save parent file information

- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/adapter/BlobRegisterAdapter.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/model/EventGridData.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/model/EventGridEvent.java
- src/main/resources/application.yml
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/event/EventHandlerTest.java
This PR proposes a mechanism to retrieve sender information from event.
It also refactor the content length retrieval, adding a new EventGridData class.
- add sender retrieve mechanism
- refactor blob size retrieval mechanism
- update tests
This changes allows us to store nearly every information related to the event, applying the event sourcing paradigm.
> [TAE-120] Save sender information

- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/adapter/BlobRegisterAdapter.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/event/EventHandlerTest.java
This PR proposes to fix broken pattern matching for sender ade ack events.
- fix pattern matching for sender ade ack events.
- update tests
This change allows us to store correctly sender ade ack blob deposit.
> [TAE-135] Fix sender ade ack container match

- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/controller/RestController.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/controller/RestControllerImpl.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/model/SenderAdeAckListDTO.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/service/FileMetadataService.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/service/FileMetadataServiceImpl.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/controller/RestControllerTest.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/service/FileMetadataServiceTest.java
This PR proposes to change the returned sender ade ack list as DTO.
- add SenderAdeAckDTO
- update test
This change is needed to be compatible with the latest batch service version.
> [TAE-89] Return ade ack as json

- .devops/deploy-pipelines.yml
- docker-compose.yml
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/adapter/BlobRegisterAdapter.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/controller/RestController.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/controller/RestControllerImpl.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/event/EventHandler.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/model/EventGridData.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/model/EventGridEvent.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/model/FileApplication.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/model/FileMetadata.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/model/FileStatus.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/model/FileType.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/model/SenderAdeAckListDTO.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/repository/FileMetadataRepository.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/service/FileMetadataService.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/service/FileMetadataServiceImpl.java
- src/main/resources/application.yml
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/controller/RestControllerTest.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/event/EventHandlerTest.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/service/FileMetadataServiceTest.java
This PR promotes the microservice to UAT environment.
> Promote to UAT

- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/model/FileMetadata.java
This PR proposes to remove event size mandatory.
- remove NotNull annotation on metadata size field.
Due to the impossibility of retrieving event size in case of HTTPS calls, the size must be removed to do not reject the request.
> [TAE-152] Remove mandatory size

- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/adapter/BlobRegisterAdapter.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/event/EventHandlerTest.java
This PR proposes to adapt existing tests and methods to new naming convention.
- adapt prent extractor method.
- adapt tests.
After a naming convention change the code is adapted.
> [TAE-166] Adapt to new AdE aggregates naming convention

- docker-compose.yml
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/adapter/BlobRegisterAdapter.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/controller/RestController.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/controller/RestControllerImpl.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/service/FileMetadataService.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/service/FileMetadataServiceImpl.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/controller/RestControllerTest.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/event/EventHandlerTest.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/service/FileMetadataServiceTest.java
This PR proposes to change file register internal interface for sender ade ack API.
- change sender ade ack endpoint interface.
- update existing tests.
Given the changes on interface of sender auth, the file register need to accept a list of sender codes as parameters.
The response is the list of sender ade acks not download yet for all the senders passed as parameters.
> [RTD-523] AdE acks for sender list

- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/controller/RestController.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/service/FileMetadataService.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/service/FileMetadataServiceImpl.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/service/FileMetadataServiceTest.java
This PR proposes to add a service method to update a file status.
- add update status method
- add custom exception in case of status already set to desired one
- update test.
This change prepares the microservice to accept AdE errors explicit ACK calls.
> [RTD-551] Update file status

- postman/local_file_register_integration_test.postman_collection.json
This PR proposes to update the Postman collection of the micro service.
After recent changes of interface and added features, the Postman collection needed an update.
This also ensures a working collection for testing automation purposes.
> [RTD-534] Update Postman collection

- Dockerfile
This PR proposes to enable Application Insights agent.
> [RTD-749] Enable Application Insights agent

- manifests/deployment.yml
This PR proposes to add a reference to Application Insights secret.
- add secret reference to manifest.
This change allows the microservice to retrieve Application Insights connection string once deployed.
> [RTD-755] add Application Insights secret reference to deployment manifest

- Dockerfile
- manifests/deployment.yml
This PR proposes to reference File Register config map during deployment.
- add reference to file register config map
- remove java agent option in Dockerfile (it is recovered from `JAVA_TOOLS_OPTIONS` in config map)
With this PR we can fully customize file register behaviour with backend changes to its config map.
> [RTD-756] Reference file register config map

- .github/PULL_REQUEST_TEMPLATE.md
Bring pull request template sections ("How has this been tested", "Types of changes") into alignment with RFC-Testing document and semver policy, respectively.
> [RTD-909] update pull request template

- .github/workflows/anchore.yml
- Dockerfile
- pom.xml
This PR proposes to add a GitHub workflow to scan security.
- New GitHub workflow
> [RTD-567] Add workflow for security scan

- manifests/deployment.yml
- src/main/resources/application.yml
This PR adds producer and connection string to projector eventhub.
- Added secret ref to deployment
- Added environment variable refs to spring application
> [RTD-938] Connect to Projector queue

- manifests/deployment.yml
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/AppConfiguration.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/adapter/FileChangedEventListener.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/domain/events/FileChanged.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/domain/events/FileChangedFactory.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/domain/events/TypeStatusFileChangedFactory.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/service/FileMetadataServiceImpl.java
- src/main/resources/application.yml
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/service/FileMetadataServiceTest.java
> [RTD-878] File register events

- .github/workflows/pr-title.yml
- .github/workflows/release.yml
- pom.xml
> [RTD-817] Semantic release

- .devops/deploy-pipelines.yml
- .github/CODEOWNERS
- .github/PULL_REQUEST_TEMPLATE.md
- .pre-commit-config.yaml
- docker-compose.yml
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/adapter/BlobRegisterAdapter.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/domain/DefaultNamingPolicyTest.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/event/EventHandlerTest.java
This PR proposes to inhibit file already present warning if the evaluated file is coming from Agenzia delle Entrate.
- modify warning condition
- increase severity from warning to error
- refactors and improvements
With this change we can set an alarm on "file already present" without triggering it with files sent with SFTP.
> feat: [RTD-1120] Remove AdE ACK already present warning

- .devops/cstar-rtd-code-review-pipelines.yml
- .devops/cstar-rtd-deploy-pipelines.yml
- helm/rtd/.helmignore
- helm/rtd/Chart.yaml
- helm/rtd/values-dev.yaml
- helm/rtd/values-prod.yaml
- helm/rtd/values-uat.yaml
- helm/rtd/values.yaml
This PR adds helm chart and pipelines to deploy to new aks
> chore: [RTD-1075] helm chart and pipelines

- pom.xml
- src/main/resources/application.yml
This PR enables health probes, which are mandatory to deploy to new aks. Health probes are provided by spring actuator
> chore: [RTD-1131] Enable spring actuator health probes

- .devops/deploy-pipelines.yml
> chore: [RTD-1078] Disable dev and uat deploy to old cluster

- Dockerfile
- src/main/resources/application.yml
- bump Application Insights agent version
- set logging level for kafka to WARN
> chore: [RTD-1217] Bump Application Insights agent version

- helm/rtd/values.yaml
> fix: [RTD-1455] Fix AppInsights problem

- .devops/cstar-rtd-deploy-pipelines.yml
> fix: [RTD-1469] fix pipeline tag and change var name

- .devops/cstar-rtd-code-review-pipelines.yml
This PR fixes code review pipeline trigger
> chore: [RTD-126] code review pipeline trigger

- pom.xml
> chore: [RTD-1616] align pom version to v1.0.0

- pom.xml
> chore: promotion to uat - align pom version to v1.0.0

- .devops/cstar-rtd-deploy-pipelines.yml
> fix: add kubectlInstaller to deploy pipeline

- .devops/cstar-rtd-deploy-pipelines.yml
- Dockerfile
- pom.xml
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/service/FileMetadataServiceImpl.java
- src/main/resources/application.yml
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/service/FileMetadataServiceTest.java
> Promotion to UAT

- .github/workflows/release.yml
- pom.xml
> fix: [RTD-1776] fix pinning release

- .github/workflows/release.yml
- pom.xml
* [RTD-1776] fix pinning release
* [RTD-1776] update version
[RTD-1776]: https://pagopa.atlassian.net/browse/RTD-1776?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RTD-1776]: https://pagopa.atlassian.net/browse/RTD-1776?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Promote to UAT

- .github/workflows/release.yml
- pom.xml
Reverts pagopa/rtd-ms-file-register#103
> chore: Revert "fix: [RTD-1776] fix pinning release"

- .github/workflows/release.yml
- pom.xml
> chore: Promote to UAT

- .github/workflows/release.yml
- pom.xml
> fix: RTD-1776 fix release pinning

- Dockerfile
- helm/rtd/values.yaml
- pom.xml
> fix: [RTD-1805] run container as non-root user

- Dockerfile
This PR proposes to place the correction needed to run the container as non root. In particular:
- install the adduser command
- create a new user
- change permission on the /app directory to let the new user to run it
- set the user
> fix: [RTD-1805] running as non root for amazoncorretto

- .github/workflows/release.yml
- Dockerfile
- helm/rtd/values.yaml
- pom.xml
> fix: Promotion to Prod - run as non-root

- helm/rtd/values-prod.yaml
- helm/rtd/values.yaml
This PR allow the microservice to connect to new rtd-platform-events queue in DEV and UAT while keeping PROD to old evh-ns
> chore: [RTD-1896] Update helm chart to use new rtd evh

- Dockerfile
- helm/rtd/values.yaml
- pom.xml
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/controller/RestController.java
This PR proposes to update spring boot and its dependencies
package | old version | new version
-- | -- | --
spring boot | 3.0.7 | 3.1.2
spring cloud | 2022.0.2 | 2022.0.4
snakeyaml | 2.0 | 2.1
run image | amazoncorretto:17.0.7-al2023-headless | amazoncorretto:17.0.8-alpine3.18
build image |  maven:3.9.0-amazoncorretto-17 |  maven:3.9.3-amazoncorretto-17
appinsights | 3.4.13 | 3.4.15
swagger-annotations | 1.6.10 | 2.2.15
> chore: [RTD-1878] update docker file and dependencies

- pom.xml
package | old version | new version
-- | -- | --
spring boot | 3.1.2 | 3.1.3
> chore: [RTD-1878] update spring boot and kafka.version

- helm/rtd/values-prod.yaml
- helm/rtd/values.yaml
> Promote to PROD

- helm/rtd/values-prod.yaml
This PR enable to use new platform-events queue from PROD env
- remove of overridden prod properties to use the default ones
> chore: [RTD-1905] Update helm chart to use new rtd evh

- helm/rtd/values-prod.yaml
> chore: update helm chart to use new rtd evh (#126)

- helm/rtd/values-prod.yaml
> chore: deploy to Prod

- pom.xml
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/adapter/FileChangedEventListener.java
- src/main/resources/application.yml
This PR tries to fix the unexpected behavior on the kafka producer: the streambridge sometimes "freeze" for 30 seconds and keep the http thread busy till the client goes in timeout.
- make explicit the property `sync: false` (it should be default but better safe than sorry)
- create the producer binder at startup time. Hopefully the fake producer will keep the binder alive and ready to respond
> fix: [RTD-1978] explicit producer binder async

- pom.xml
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/adapter/FileChangedEventListener.java
- src/main/resources/application.yml
This PR proposes to promote in uat the changes on the producer binder to solve the stale problem on the StreamBridge.
> fix: promotion to UAT - producer binder

- pom.xml
> feat: opentelemetry

- pom.xml
> feat: opentelemetry (#140)

- .github/workflows/scan.yml
This PR proposes to replace the scan engine Grype with Trivy.
Due to the false positives detection of Grype, Trivy might be the solution to have a quality scan on docker image.
The scan workflow has been modified accordingly to requirement => the action must fail when a cve high or critical has been detected. An ad-hoc step has been added in order to do so.
> chore: [RTD-2081] replace grype with trivy

- .github/workflows/scan.yml
> chore: Promotion to UAT - replace grype with trivy

- .github/workflows/scan.yml
- pom.xml
> chore: promotion to main - replace grype

- pom.xml
This PR proposes to update the kafka dependency version to fix the snappy cve on it.
> fix: [RTD-2133] update kafka dependency for snappy cve

- pom.xml
> fix: promotion to uat - update kafka version

- .github/workflows/scan.yml
- pom.xml
> fix: promotion to main - update kafka dependency

- src/main/resources/application.yml
This PR proposes to increase the log level on Kafka library from `WARN` to `INFO`. The change is aimed to catch any suspect behavior behind the delay on the streamBridge publishing.
> chore: relax log level on kafka

- src/main/resources/application.yml
> chore: relax log level on kafka (#150)

- pom.xml
- src/main/resources/application.yml
> chore: promotion to prod - relax log kafka

- Dockerfile
- pom.xml
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/adapter/FileChangedEventListener.java
- src/main/resources/application.yml
This PR proposes to change the kafka configuration in a compliant way with azure event hub recommended settings.
| package | old version | new version |
| --- | --- | --- |
| spring boot | 3.1.3 | 3.1.5 |
| snakeyaml | 2.1 | 2.2 |
| run image | amazoncorretto:17.0.8-alpine3.18 | amazoncorretto:17.0.9-alpine3.18 |
| modelmapper | 3.1.1 | 3.2.0 |
| swagger-annotations | 2.2.15 | 2.2.18 |
> fix: [RTD-2155] change kafka producer properties to azure standards

- Dockerfile
- pom.xml
- src/main/resources/application.yml
> fix: promotion to UAT - change kafka producer properties

- helm/rtd/values.yaml
- pom.xml
- src/main/resources/logback-spring.xml
> fix: [RTD-2260] Wrong otel logging filter (#157)

- .github/CODEOWNERS
Description
This PR use team as codeowner
List of Changes
updated file
Motivation and Context
[Operational Excellence Task](https://pagopa.atlassian.net/browse/OE-143)
> docs: CODEOWNERS

- Dockerfile
- pom.xml
This PR proposes to update the runtime docker image to solve the following CVE:
- https://avd.aquasec.com/nvd/cve-2023-5678
- https://avd.aquasec.com/nvd/cve-2023-5363
> fix: [RTD-2297] update runtime docker image to solve cve

- Dockerfile
- helm/rtd/values.yaml
- pom.xml
- src/main/resources/logback-spring.xml
> fix: promotion to UAT - fix cve

- helm/rtd/values-dev.yaml
- helm/rtd/values-uat.yaml
This PR proposes to enable the forceRedeploy flag in the helm deployment configuration. The pod rollout will happen automatically now and there is no needed of manual deployment restart to spin up the new pods.
> chore: [RTD-2303] enable force redeploy flag

- helm/rtd/values-dev.yaml
- helm/rtd/values-uat.yaml
> chore: promotion to UAT - enable forceRedeploy

- pom.xml
Update dependencies
| Dependecy | Previews version | Updated version | 
| --- | --- | --- |
| `spring boot` | `3.1.5` | `3.2.1` |
| `snakeyaml` | `2.0` | `2.2` |
| `testcontainers` | `1.17.6` | `1.19.3` |
| `testcontainers-junit-jupiter` | `1.17.6` | `1.19.3` |
| `testcontainers-mongodb` | `1.17.6` | `1.19.3` |
| `reactor-netty-http` | `1.1.11` | `1.1.14` |
| `reactor-netty-core` | `1.1.11` | `1.1.14` |
> chore: [RTD-2309] update spring boot version

- helm/rtd/values-prod.yaml
Literally, the code wants to express this:
_I want_ **2** _pods replicas and the pods must be inside a node with label key_ **node_type** _and the label value must be_ **user**, _beyond that is preferred that the pods will be not scheduled in the_ **topology.kubernetes.io/zone** _zone and namespace_ **rtd** _where is present another pod labeled_ **app.kubernetes.io/instance=rtd-ms-file-reporter**.
> chore: [RTD-2326] add 2 replicas in different nodes for prod env

- helm/rtd/values.yaml
Update startup readiness liveness time params.
> chore: [RTD-2404] update startup readiness liveness time

- Dockerfile.native
- pom.xml
This PR proposes to update the spring boot version and the docker image runtime.
dep | old version | new version
-- | -- | --
spring boot | 3.2.1 | 3.2.3
image runtime | ubuntu:noble-20231221 | ubuntu:noble-20240225
> fix: [RTD-2459] update docker image runtime & spring boot

- Dockerfile.native
- helm/rtd/values.yaml
- pom.xml
> fix: promotion to prod - fix cve

- .github/workflows/scan.yml
- pom.xml
> fix: remove fixed spring-core version

- .github/workflows/pr-title.yml
- .github/workflows/release.yml
- .github/workflows/scan.yml
- .github/workflows/send-notification.yml
- Dockerfile.native
- pom.xml
This pr split scan action and updates dependencies, images, and actions.
> chore: [RTD-2571] update dependencies, action and images

- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/domain/events/DecryptedEventCommand.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/service/FileMetadataServiceImpl.java
> chore: [RTD-2578] change logs level

- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/adapter/BlobRegisterAdapter.java
> chore: [RTD-2579] change condition and change warning level to info

- .github/workflows/scan.yml
- pom.xml
> chore: [RTD-291] fix cve and github action

- .github/workflows/release.yml
- .github/workflows/scan.yml
- .github/workflows/send-notification.yml
- Dockerfile.native
- pom.xml
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsfileregister/telemetry/AppInsightConfig.java
- src/main/resources/application.yml
- upgrade spring boot to 3.3.4
- upgrade opentelemetry to 1.43.0
- upgrade opentelementry-instrumentation to 2.9.0 (target SDK 1.43.0)
- upgrade azure exporter to 1.0.0-beta.30 (target SDK 1.43.0)
- upgrade github actions
- removed mongodb manual instrumentation cause 2.9.0 provided it automatically
- 
> fix: [TAE-338] update dependencies

- pom.xml
Updating to the latest version (v0.29.0) of trivy action by pinning the hash.
https://github.com/pagopa/rtd-ms-file-register/pull/212
> chore: TAE-353-update-version-trivy-action

- pom.xml
Updated `spring-boot` version from `3.3.5` to `3.4.1` to resolve the CVE. Also updated the `spring-cloud.version` from `2023.0.2` to `2024.0.0` for Spring Boot compatibility.
Updated micriservice version from `2.0.1` to `2.0.2`.
- pom.xml
High CVE in Tomcat.
> fix: [TAE-356] high CVE in Tomcat

- .devops/cstar-rtd-code-review-pipelines.yml
- .devops/cstar-rtd-deploy-pipelines.yml
- helm/rtd/values.yaml
- pom.xml
> fix: [TAE-366] Promotion UAT 

- Dockerfile
- Dockerfile.native
- pom.xml
Migrated Docker Registry to AWS ECR.
From April 1st unauthenticated and Docker Personal users are subject to a 6-hour pull rate limit on Docker Hub.
https://docs.docker.com/docker-hub/usage/pulls/
> chore: [TAE-367] migrate docker registry to aws
